My first version of the password generator
midudev/password-generator pull request #154
Opened 2022-10-03 20:52 UTC by IcarusTheFly

2022-10-06 20:43 UTC, midudev commented on src/components/icarusthefly/App.css
> +body {
Los estilos tienen que estar scopeados con tu nombre de usuario. Esto es para evitar que tus estilos machaquen estilos de la página y otras soluciones.

Por ejemplo #icarusthefly body { ... }

2022-10-06 20:44 UTC, midudev requested changes
Falta scopear los estilos.

2022-10-22 16:25 UTC, IcarusTheFly commented on src/components/icarusthefly/App.css
> +body {
Gracias! Hecho :)

2022-10-23 20:59 UTC, maadeval approved these changes
Hola!! 👋 Muchas gracias por scopear los estilos! Quedó todo perfecto 😊

2022-10-23 21:00 UTC, merged