First steps
midudev/password-generator pull request #164
Opened 2022-10-03 22:30 UTC by rogerparada

Password generator button
Slider
Copy button

2022-10-07 22:32 UTC, maadeval requested changes

2022-10-07 22:32 UTC, maadeval commented on src/components/rogerparada/PasswordGenerator.vue
> +import icon from './assets/images/iconCopy.svg'
Hola!! 👋 El error del build es porque no se ha podido encontrar este directorio! Te dejo la solución aquí abajo! 👇
```suggestion
import icon from './assets/images/IconCopy.svg'
```

2022-10-08 08:49 UTC, rogerparada commented on src/components/rogerparada/PasswordGenerator.vue
> +import icon from './assets/images/iconCopy.svg'
Gracias, corregido y subido.

2022-10-08 14:41 UTC, maadeval approved these changes

2022-10-09 10:36 UTC, merged