update soluction
midudev/password-generator pull request #169
Opened 2022-10-03 23:33 UTC by DiegoCadavid

2022-10-07 22:43 UTC, maadeval requested changes
Hola!! 👋 Los estilos en tu fichero `src/components/diegocadavid/app.css` tiene que estar scopeados con tu nombre de usuario para que no entre en conflicto con otras soluciones!

**Alternativa:**
Otra opción es transformar ese fichero a `src/components/diegocadavid/app.module.css` para que el nombre de las clases se generen con un identificador único!

Muchas gracias por tu solución! Me encantó!!! 🚀😊

2022-10-08 16:34 UTC, DiegoCadavid commented
@maadeval Listo! el nombre de archivo, clases y keyframes están scopeados con mi user

2022-10-08 16:34 UTC, DiegoCadavid commented
@maadeval Listo! el nombre de archivo, clases y keyframes están scopeados con mi user

2022-10-08 19:16 UTC, maadeval approved these changes

2022-10-08 19:17 UTC, maadeval commented
Muchas gracias!! 🎉

2022-10-09 10:29 UTC, merged