my password generator
midudev/password-generator pull request #173
Opened 2022-10-04 00:06 UTC by Daviddlh1

Hola Esta es mi version del generador de contraseñas

2022-10-06 20:48 UTC, midudev requested changes
Hay que hacer que los estilos estén scopeados.

Puedes usar tu nombre de usuario con un elemento que envuelva tu app.

<div id="daviddlh1">...</div>

Y en el css:
#daviddlh1 .password-generator__wrapper {...}

2022-10-06 22:32 UTC, Daviddlh1 commented
Hola acbo de hacer el cambio, nunca he hecho esto, si aparecen reflejados?

2022-10-06 22:40 UTC, Daviddlh1 commented
Ya pude ver mi pr en la pagina gracias :)

2022-10-09 10:30 UTC, merged

2022-10-09 17:50 UTC, Daviddlh1 commented
Gracias :)