add Password generator - cechus
midudev/password-generator pull request #186
Opened 2022-10-04 05:13 UTC by cechus

2022-10-09 11:36 UTC, midudev commented
El error es este:
<img width="1049" alt="CleanShot 2022-10-09 at 13 35 21@2x" src="https://user-images.githubusercontent.com/1561955/194754683-61461b02-f0d8-49a6-a430-41678db604fd.png">

Revisa que el import del archivo esté bien. Ten en cuenta que los imports en Linux son case-sensitive.

2022-10-09 19:12 UTC, H4rasho commented
> El error es este: <img alt="CleanShot 2022-10-09 at 13 35 21@2x" width="1049" src="https://user-images.githubusercontent.com/1561955/194754683-61461b02-f0d8-49a6-a430-41678db604fd.png">
> 
> Revisa que el import del archivo esté bien. Ten en cuenta que los imports en Linux son case-sensitive.

Tuve el mismo problema puedes elimnar la extención .jsx de los imports. a mi me funcinó.

2022-10-10 14:08 UTC, cechus commented
> > El error es este: <img alt="CleanShot 2022-10-09 at 13 35 21@2x" width="1049" src="https://user-images.githubusercontent.com/1561955/194754683-61461b02-f0d8-49a6-a430-41678db604fd.png">
> > Revisa que el import del archivo esté bien. Ten en cuenta que los imports en Linux son case-sensitive.
> 
> Tuve el mismo problema puedes elimnar la extención .jsx de los imports. a mi me funcinó.

Gracias, me funciono eliminando el .jsx

2022-10-10 22:15 UTC, maadeval requested changes
Hola!! 👋 Los estilos de `input` en el fichero `src/components/cechus/PasswordGenerator.module.css` tienen que estar scopeados con tu nombre de usuario para que no entre en conflicto con otras soluciones o estilos de la página!

**Alternativa:**
También puedes estilarlos a partir de una `custom class` (al usar CSSModules se generará con un identificador único y no entrará en conflicto con otras soluciones).

> CSSModules genera identificadores únicos pero solo a selectores de tipo `class`, lo que estiles a partir de referencias a elementos HTML no será scopeado y estilará todas las etiquetas que encuentre en el sitio.

Muchas gracias por tu solución! 😊

2022-10-10 22:42 UTC, cechus commented
> Hola!! wave Los estilos de `input` en el fichero `src/components/cechus/PasswordGenerator.module.css` tienen que estar scopeados con tu nombre de usuario para que no entre en conflicto con otras soluciones o estilos de la página!
> 
> **Alternativa:** También puedes estilarlos a partir de una `custom class` (al usar CSSModules se generará con un identificador único y no entrará en conflicto con otras soluciones).
> 
> > CSSModules genera identificadores únicos pero solo a selectores de tipo `class`, lo que estiles a partir de referencias a elementos HTML no será scopeado y estilará todas las etiquetas que encuentre en el sitio.
> 
> Muchas gracias por tu solución! blush

Hola gracias por la obersvación, ya subí los cambios que solucionan el error.

2022-10-10 22:51 UTC, maadeval approved these changes

2022-10-10 22:51 UTC, merged

2022-10-10 22:55 UTC, maadeval commented
Cambios mergeados!! 🙌 Muchas gracias!!