[FEATURE] Solucion basica con todos los requisitos
midudev/password-generator pull request #212
Opened 2022-10-04 18:38 UTC by LcsGrz

Esta es la solucion super simple y basica para abarcar todos los requisitos

2022-10-06 20:28 UTC, midudev commented on src/components/LcsGrz/Page.css
> +.container {
Hay que hacer que los estilos tengan un scope propio. Puedes usar tu nombre de usuario en los selectores para que no colisione con los estilos de otras personas.

2022-10-09 11:16 UTC, midudev requested changes
Evitar que los estilos entren en conflicto con otras soluciones.

2022-10-23 21:31 UTC, maadeval requested changes
Hola! 👋 Muchas gracias por tu solución! Las clases en tus ficheros `css` tienen que tener un nombre único que no sea usado en el sitio o en otras soluciones, esto es para evitar conflictos!

Por ejemplo: la clase `icon-container` puede estar siendo usada en otra parte del sitio y los estilos se sobreescribirian. Para solucionarlo hay varias alternativas (te comento dos):

**1- Scopear tus estilos con tu nombre de usuario**
En el fichero `index.astro`
```astro
<div class='h-screen flex items-center justify-center' id="LcsGrz">
    <Page client:visible />
</div>
```
Y luego en tus ficheros `css` englobar tus clases a partir de ese id
```css
#LcsGrz .ccontainer {
    ...
}

#LcsGrz .icon-container {
    ...
}
```
Esto puede resultar muy tedioso, así que te comento la segunda solución que creo que te será más útil!

**2- Usar CSSModules para generar tus clases con un identificador único**
Lo único que habría que hacer es cambiar el prefijo `[...].css` a `[...].module.css` (no olvides cambiarlo también en las importaciones!), y solo con eso tus estilos estarán siendo generados con un identificador único que no va a entrar en conflicto con otras soluciones.

Con ese cambio ya podremos mergear tu solución! 🚀

2022-10-31 04:12 UTC, LcsGrz commented
@midudev Hola! a ver si ahora si esta bien, sabes que habia olvidado que habia habierto este PR y olvide mirar tus comentarios, me quede con el primero que me dejaste :(
Encuentro que me diste soluciones copadas pero lo e resuelto de la siguiente manera

nombre-componente-nombreDeLaClase --> lg-h-container

Es util o lo modifico rapidisimo a lo que me comentabas?

2022-11-01 02:05 UTC, maadeval requested changes
Hola!! Muchas gracias por el gran cambio que hiciste!!! Lo valoro mucho ⚡️ De igual manera para asegurarnos de que las clases no entren en conflicto de ninguna manera voy a pedirte si puedes scopearlo con tu nombre de usuario, algo que puede agilizar el trabajo es hacer un hibrido en lo que te comenté y lo que tienes hecho! 🚀 Puedes agregar tu nombre de usuario de esta manera:
```css
.lcsgrz-am-container {}
.lcsgrz-h-title-box  {}
```
Usando el buscador de VSCode y remplazando el texto de `.lg-` por `.lcsgrz-` se puede hacer menos tedioso 😅

Muchas gracias otra vez por merjorarlo!! 😊

2022-11-01 03:31 UTC, LcsGrz commented
@maadeval Listo! ya cambie todas las ocurrencias :D

2022-11-01 12:22 UTC, maadeval approved these changes
Excelente!! 😎 Ahora si, muchas gracias!! Ya quedará mergeado 🚀

2022-11-01 12:24 UTC, merged