Eddcode random password
midudev/password-generator pull request #223
Opened 2022-10-05 00:21 UTC by EddCode

#### Primera fase del reto

* Slider que toma la longitud deseada de la contraseña
* Botón para copiar la contraseña
* Botón que genera la contraseña

2022-10-09 10:21 UTC, midudev commented on src/components/EddCode/Password/styles.css
> +.password-box {
Hay que hacer que los estilos estén scopeados con tu nombre de usuario para hacerlos únicos a tu solución y que no entren en conflicto con otros.

2022-10-09 10:24 UTC, midudev reviewed
Chequea lo de los estilos :)

2022-10-20 18:40 UTC, EddCode commented on src/components/EddCode/Password/styles.css
> +.password-box {
Quedo listo

`.eddcode-password-box`

2022-10-25 23:35 UTC, maadeval requested changes
Hola! 👋 Muchas gracias por scopear los estilos! ⚡️ En el último commit se agregaron cambios de código y estilo de comillas en otras soluciones, podrias remover esos cambios?

Con eso ya quedaría perfecto y mergeariamos la solución 😊

2022-10-28 15:29 UTC, maadeval requested changes
Hola! Gracias por mejorar tu solución! 🚀 

Para mergearlo no deben haber cambios en soluciones de otros particpantes `src/components/garu2/PasswordGenerator.astro`.

Puedes remover los cambios de ese fichero? Como alternativa puedo removerlo desde las herramientas de Github, si lo prefieres me avisas y lo remuevo desde aquí 😊

2022-10-28 17:47 UTC, EddCode commented
@maadeval Podrías revertir los cambios?, porfavor

2022-10-29 16:06 UTC, maadeval approved these changes
Listo! 🚀  Ya quedó listo para mergear, muchas gracias por contribuir! 🙌

2022-10-29 16:06 UTC, merged