creating index.astro (eyubkh)
midudev/password-generator pull request #329
Opened 2022-10-12 20:46 UTC by eyubkh

# ⭐ Descripción

Pull request inicial con carpetas creadas en entrys, components y public.

## 🚀 Tipo de cambio

- [ ] Arreglo de bug (cambios que no rompen nada y resuelven un problema).
- [X] Nueva característica (cambios que no rompen nada y agregan funcionalidad).
- [ ] Cambio radical (arreglo o característica que podría causar que una funcionalidad no funcione como se espera).
- [ ] Este cambio requiere actualización de documentación.

# 🤔 ¿Cómo ha sido probado este cambio?

*Describa las pruebas que ha realizado para verificar los cambios. Proporcione 
instrucciones para que podamos reproducirlos. Por favor, indique también cualquier detalle relevante 
para la configuración de su prueba. Ejemplo:*

- [ ] Prueba A
- [ ] Prueba B

**Configuración de pruebas**:
- Versión de Node:
- Versión de Astro:

# 📝 Lista de verificación:
(*) -> obligatorio.

- [X] Mi código sigue [las reglas](https://github.com/midudev/password-generator#-reglas) de este proyecto *.
- [X] He creado mis propias clases / ids y he comprobado que no afectan a otros diseños de la comunidad *.
- [X] He realizado una auto-revisión de mi propio código *.
- [ ] He comentado mi código, particularmente en las áreas difíciles de entender.
- [X] Mis cambios no generan nuevos avisos *.
- [X] No he instalado nuevos módulos con `npm install` o `yarn install` *.
- [X] La solución es de mi autoría y no he copiado código de otros participantes *.
- [X] No modifiqué ningún otro archivo más que los míos *.

2022-10-13 22:28 UTC, maadeval requested changes
Hola!! 👋 Muchas gracias por scopear tus estilos con tu nombre de usuario! 🚀

En el directorio `src/components/eyubkh/style/animation.css` quedaron dos `keyframes` (`show` y `hide`) que pueden entrar en conflicto con los estilos globales del sitio.

Te adjunto una imagen para que puedas verlo mejor! Al cargar el sitio, el fichero que te mencioné se descarga y sus clases quedan accesibles a su uso! Si hay algún keyframe con ese mismo nombre, puede entrar en conflicto 😭

<img width="1440" alt="Captura de Pantalla 2022-10-13 a la(s) 18 56 11" src="https://user-images.githubusercontent.com/55862658/195722258-ff9eb218-e69e-43fa-a2fb-3820f5e6444a.png">


**Alternativa**
Por lo que estuve viendo en el código, esos keyframes no son usados, puedes optar por removerlos o anidarlo con tu`username`, por ejemplo:
```css
@keyframes eyubkh-show {
    ...
}
```

Muchas gracias por tu solución!! 😊

2022-10-18 12:51 UTC, eyubkh commented
ouh se me olvido borrarlo 😅
lo he borrado y he añadido la carpeta /utils donde he añadido la logica.

lo he revisado y ahora parece que no hay conflicto 🤞🏽

2022-10-18 21:23 UTC, maadeval approved these changes

2022-10-18 21:24 UTC, merged

2022-10-18 21:24 UTC, maadeval commented
Holaaa! Todo perfecto! 🥳 Ya quedan tus cambios mergeados! Muchas gracias por solucionarlo! 🙌