App terminada, kebab-case, eliminado empty-block, jsx corregido
midudev/password-generator pull request #376
Opened 2022-10-28 02:21 UTC by kurotom

# ⭐ Descripción

Terminé la app, Hacktoberfest!.

2022-10-28 17:57 UTC, kurotom commented
Solicito revisión y eventual aprobación para unir al proyecto principal.

2022-10-29 18:30 UTC, maadeval requested changes
Hola!! 👋 Los estilos en tus ficheros `[...].css` tienen que estar scopeados con tu nombre de usuario para que no entre en conflicto con otras soluciones o estilos de la página!

Te dejo un ejemplo:
```css
#kurotom .opciones-check {
  ...
}

/* otra alternativa es agregar tu nombre de usuario en el propio nombre de clase */
#kurotom-btn {
...
}
```
**Alternativa:**
Otra opción es transformar esos ficheros a `[...].module.css` para que el nombre de las clases se generen con un identificador único!

Muchas gracias por tu solución! 😊

2022-10-29 21:19 UTC, kurotom commented
Hola, ya hice los cambios en los estilos del fichero .css, espero la revisión.

2022-10-29 22:03 UTC, maadeval approved these changes
Todo perfecto! 🚀 Muchas gracias por tu solución 😊 Ya quedará mergeado!

2022-10-29 22:04 UTC, merged

2022-10-29 22:58 UTC, kurotom commented
Muchas gracias!