andresin87 contribution
midudev/password-generator pull request #382
Opened 2022-10-30 00:04 UTC by andresin87

# ⭐ Descripción

*Por favor, incluye una breve descripción de tus cambios.*
Aqui va mi primera contribución a las hackatones de @midudev. No se ni cómo me ha dado tiempo de participar después de pasarme un hacktoberfest repleto de contribuciones al OpenSource tanto como maintainer como contributor. Es admirable el trabajo que estas haciendo. Me alegro de que te estén saliendo tan bien todas estas iniciativas y deseo que vaya a mucho mas.

## 🚀 Tipo de cambio

- [ ] Arreglo de bug (cambios que no rompen nada y resuelven un problema).
- [x] Nueva característica (cambios que no rompen nada y agregan funcionalidad).
- [ ] Cambio radical (arreglo o característica que podría causar que una funcionalidad no funcione como se espera).
- [ ] Este cambio requiere actualización de documentación.

# 🤔 ¿Cómo ha sido probado este cambio?

*Describa las pruebas que ha realizado para verificar los cambios. Proporcione 
instrucciones para que podamos reproducirlos. Por favor, indique también cualquier detalle relevante 
para la configuración de su prueba. Ejemplo:*

- He cuidado  la UX (navegable por teclado, informar de elementos interactuables con hovers, focus)
- He respetado la UI y las brand-guidelines
- permite seleccionar passwords de distintos largos
- permite elegir entre cualquier combinatoria (AND) de patrones: [mayucula, minuscula, numerico, simbolos]
- el sistema retorna una puntuación al password en función de la seguridad [1-4]
- permite cambiar light-dark mode (el light es muy malo XD)
- he recreado el logo de la web de hacktoberfest
- he separado la logica de la vista
- Tenia pensado hacer un finguerprint icon (similar a la huella de apple) mostrando la seguridad pero no lo he incluido al final en el código pk me faltaba cuidar su integración visual con el resto de elementos (necesito entregar y no aporta un valor significativo)

**Configuración de pruebas**:
- Versión de Node:
- Versión de Astro:

# 📝 Lista de verificación:
(*) -> obligatorio.

- [x] Mi código sigue [las reglas](https://github.com/midudev/password-generator#-reglas) de este proyecto *.
- [x] He creado mis propias clases / ids y he comprobado que no afectan a otros diseños de la comunidad *.
- [x] He realizado una auto-revisión de mi propio código *.
- [ ] He comentado mi código, particularmente en las áreas difíciles de entender.
- [x] Mis cambios no generan nuevos avisos *.
- [x] No he instalado nuevos módulos con `npm install` o `yarn install` *.
- [x] La solución es de mi autoría y no he copiado código de otros participantes *.
- [x] No modifiqué ningún otro archivo más que los míos *.

2022-10-30 00:15 UTC, andresin87 commented
no puedo ver qué ha fallado en vercel

2022-10-30 16:50 UTC, maadeval requested changes
Muchas gracias por scopear todas tus clases! 🚀

Hay ficheros como `src/pages/entry/oswaldev/index.astro` y `src/components/juanpablo-is/utils/scale-list.js` que pertenecen a otras soluciones, evita hacer cambios en ellos!

Por otro lado, el fichero `public/grain-light.png` es recomendable que esté dentro de una carpeta con tu nombre de usuario, te dejo un ejemplo:
```
public/andresin87/grain-light.png
```

En el fichero `src/components/andresin87/styles/styles.css` evita aplicar estilos a la etiqueta `body` ya que puede entrar en conflicto con los estilos globales del sitio (este CSS es descargado desde la home) y si puedes, scopea tu keyframe llamado `binary` con tu nombre de usuario para evitar el mismo problema ⚡️

Con eso ya quedaría listo para mergear, muchas gracias por tu solución y cualquier duda puedes comentarnos! 😊

2022-10-30 16:50 UTC, maadeval commented on src/components/andresin87/utils/icons/index.js
> +import iconUsers from './iconUsers.jsx'
Hola!! 👋 El error está en esta linea cuando se quiere hacer el `build` del proyecto, el fichero `IconUsers` empieza en mayúscula y su import está en minúscula, por lo que no encuentra ese fichero  😊

```suggestion
import iconUsers from './IconUsers.jsx'
```

2022-10-30 17:47 UTC, andresin87 commented
Esta noche corrijo los cambios que comentas.thks.

2022-10-30 21:47 UTC, andresin87 commented on src/components/andresin87/utils/icons/index.js
> +import iconUsers from './iconUsers.jsx'
thks

2022-10-30 23:12 UTC, andresin87 commented on src/components/andresin87/utils/icons/index.js
> +import iconUsers from './iconUsers.jsx'
done

2022-10-30 23:13 UTC, andresin87 commented
Me he dado cuenta que habia un directorio específico para hooks y los he movido ahi bajo una carpeta con mi alias

2022-10-31 00:06 UTC, maadeval approved these changes
Todo perfecto! 🚀 Muchas gracias por arreglarlo tan rápido!

Me tome el atrevimiento de generar un commit para remover un espacio en blanco que se había generado en el fichero de otra solución `src/components/juanpablo-is/utils/scale-list.js`. Aún asi, el fichero no ha desaparecido en la lista de commits, pero corroboro de que está tal cual tiene que estar y no altera su funcionamiento 😊 Así que no hay problema

Muchas gracias!!

2022-10-31 00:07 UTC, merged