password generator panda
midudev/password-generator pull request #387
Opened 2022-10-31 20:48 UTC by MaxWolts

# ⭐ Descripción

Mi password-generator

## 🚀 Tipo de cambio

- [ ] Arreglo de bug (cambios que no rompen nada y resuelven un problema).
- [ ] Nueva característica (cambios que no rompen nada y agregan funcionalidad).
- [ ] Cambio radical (arreglo o característica que podría causar que una funcionalidad no funcione como se espera).
- [ ] Este cambio requiere actualización de documentación.

# 🤔 ¿Cómo ha sido probado este cambio?

*Describa las pruebas que ha realizado para verificar los cambios. Proporcione 
instrucciones para que podamos reproducirlos. Por favor, indique también cualquier detalle relevante 
para la configuración de su prueba. Ejemplo:*

- [ ] Prueba A
- [ ] Prueba B

**Configuración de pruebas**:
- Versión de Node:
- Versión de Astro:

# 📝 Lista de verificación:
(*) -> obligatorio.

- [x] Mi código sigue [las reglas](https://github.com/midudev/password-generator#-reglas) de este proyecto *.
- [x] He creado mis propias clases / ids y he comprobado que no afectan a otros diseños de la comunidad *.
- [x] He realizado una auto-revisión de mi propio código *.
- [ ] He comentado mi código, particularmente en las áreas difíciles de entender.
- [x] Mis cambios no generan nuevos avisos *.
- [x] No he instalado nuevos módulos con `npm install` o `yarn install` *.
- [x] La solución es de mi autoría y no he copiado código de otros participantes *.
- [x] No modifiqué ningún otro archivo más que los míos *.

2022-10-31 20:50 UTC, midudev commented on src/components/maxwolts/style.css
> +.panda-face {
Le falta el prefijo de tu nombre de usuario a algunas clases de CSS. Como esta.

2022-10-31 21:16 UTC, MaxWolts commented on src/components/maxwolts/style.css
> +.panda-face {
Hi!, Ya hice un nuevo commit con el prefijo en todas las clases. 😄

2022-11-01 02:11 UTC, maadeval requested changes

2022-11-01 02:11 UTC, maadeval commented on src/components/maxwolts/style.css
> +@keyframes animation-rotate {
Holaa!! Muchas gracias por cambiarlos!! 🚀 Quedó un keyframe solitario sin el scope 👀 Solo faltaría eso y ya podremos mergearlo! 💪🏻
```suggestion
@keyframes maxwolts-animation-rotate {
```

2022-11-01 05:56 UTC, MaxWolts commented on src/components/maxwolts/style.css
> +@keyframes animation-rotate {
Hi!, listo el cambio fue hecho. 😃

2022-11-01 12:25 UTC, maadeval approved these changes
🚀🚀🚀

2022-11-01 12:26 UTC, merged

2022-11-10 20:37 UTC, javigaralva commented
Al hacer un "npm run build" genera un error en este entry:


El error parece estar en la referencia 
![image](https://user-images.githubusercontent.com/21366112/201199820-4a4f834b-b39c-43a5-89b8-c1453eb884b4.png)

El archivo index.astro intenta importar PasswordGenerator en '@components/maxwolts/PasswordGenerator' (sin extensión) y existen dos archivos y ninguno de los dos exporta PasswordGenerator.

![image](https://user-images.githubusercontent.com/21366112/201200022-b6d2d923-6910-415d-b1bf-4234c040e84e.png)

Supongo que habría que corregirlo para evitar que haya fallos en la generación de la build (desconozco si este es problema de que no haya generado la build en la última PR que he añadido.

@MaxWolts, ¿podrías echarle un ojo? 
Gracias.